### ISSUE TITLE
Cancel page load by pressing ESC

### ISSUE THREAD

**Issue by marekhrabe** [dieulot/instantclick#112]
This is expected behaviour that replicates browser experience of loading page - <kbd>ESC</kbd> immediately stops loading and leaves you on last page. 

I haven't looked into the code yet, but I can probably contribute this change if you consider it useful for this project

**Comment by dieulot** [comment]
It’s definitively a regression not to have this, but not a big enough problem to warrant fixing it (as everything complicates maintenance). This use case only happens when a page has trouble loading, **and** the user is a power-user who knows about that behavior from <kbd>ESC</kbd>, a marginal occurrence.
