### ISSUE TITLE
Suggestion: Only preload pages once per page load

### ISSUE THREAD

**Issue by robgraeber** [dieulot/instantclick#132]
Hey it seems like repeatedly mousing over over links is loading the next page multiple times. I think limiting preloading to once per page load or something like once every 30 sec would really help cut down on page loads on the backend.

**Comment by bep** [comment]
A debouncer would do it.

**Comment by bevdam** [comment]
I think it's also important to remember that once a page is preloaded it should be cached. Therefore, it should not have to hit the  server again. I also think if I am not mistaken that  if the mouse leaves the link the loading is stopped.

**Comment by robgraeber** [comment]
The pages aren't necessarily cached, when I mouseover links on instantclick.io I see a bunch of 200 requests in the network tab. Best case is 304 responses if your server supports it.

**Comment by bevdam** [comment]
Yeah HTML is never really cached but If you can I recommend doing it when using this plugin cache the pages for and hour or so. Would depend on the page content as well. If you are looking to reduce server load or update the plugin as you suggested.

**Comment by robgraeber** [comment]
It was more difficult than I expected, but I got some basic preload caching working on a fork. Seems like everything is setup to handle 1 preload at a time, so I changed it to only cache the last moused over link.

Here's the diff for reference: https://github.com/robgraeber/instantclick2/commit/b0c0443c54101def72dd78aac393c26e71d26821

Ideally it would cache multiple requests at a time, but that would take a big refactor. Or a clever way to cache XMLHttpRequest's.

**Comment by robgraeber** [comment]
Okay got the caching working with multiple requests. Didn't have to refactor too much, was able to store cached xhr objects and feed them in.

My fork: https://github.com/robgraeber/instantclick2

The diff: https://github.com/robgraeber/instantclick2/compare/bc6f9f296ff75ffdb43cdadfac0482c6ed8077d7...master

**Comment by bevdam** [comment]
This is cool

**Comment by ahmedhagii** [comment]
the first issue I noticed when I heard about instantclick, came to open an issue and found this :) great fix :+1:

**Comment by onigetoc** [comment]
On mouve hover, store the url, if another mouse hover is done, then check the last mouse hover url and do not preload it.

**Comment by dieulot** [comment]
You can use caching with InstantClick the same way you do without InstantClick: by setting `Expires` headers on the server. Implementing caching in JavaScript would be uselessly redundant. Setting caches on the server instead of in JavaScript has other benefits:
- It will work when the page is opened in another tab.
- It’s not dependant on InstantClick, so it will still work if you stop using InstantClick on your site.
- It works for browsers that don't support InstantClick.

The big benefit to implement caching in JavaScript would be that it would cache out of the box, but not every site needs caching. When you have highly-dynamic content, such as a forum where new messages get posted nearly every second, you don’t want to have lagging content.
