### ISSUE TITLE
Requesting insecure content

### ISSUE THREAD

**Issue by bobbyshaw** [dieulot/instantclick#141]
Setup: 

- Github Pages
- Cloudflare SSL

Using relative or absolute URLS, sometimes the preload gets blocked.  This means that URLs require two clicks to get to a page.

<img width="1427" alt="screen shot 2016-08-30 at 09 56 35" src="https://cloud.githubusercontent.com/assets/553566/18083159/d8016e54-6e99-11e6-8f9f-529d85c9571e.png">

```
Mixed Content: The page at 'https://tomrobertshaw.net/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://tomrobertshaw.net/projects/'. This request has been blocked; the content must be served over HTTPS.
```

It appears that the first request is for the HTTPS URL but this gets cancelled.  The second request is for HTTP which gets blocked.

<img width="1404" alt="screen shot 2016-08-30 at 09 56 40" src="https://cloud.githubusercontent.com/assets/553566/18083160/dd9df382-6e99-11e6-84a8-9963452fdc8a.png">

<img width="865" alt="screen shot 2016-08-30 at 09 56 47" src="https://cloud.githubusercontent.com/assets/553566/18083173/e531b714-6e99-11e6-93b2-08f0a8b1a011.png">

<img width="831" alt="screen shot 2016-08-30 at 09 56 50" src="https://cloud.githubusercontent.com/assets/553566/18083177/e801896a-6e99-11e6-8006-091f06a11b28.png">

I haven't been able to work out why some URLs work and some don't work with instant click.

**Comment by QuantumRevenger** [comment]
This seems to be a strange issue; have you tried formatting your urls like: //tomrobertshaw.net/projects/

**Comment by bobbyshaw** [comment]
@QuantumRevenger Yes, I tried protocol agnostic URLs and still got the same issue.

**Comment by QuantumRevenger** [comment]
@bobbyshaw it's a weird issue, I tested against my own implementation of Instant Click called 'Projective Butters' that shares the same principles and the issue does not present itself.

I'd offer my code but its highly integrated and very different from Instant Click (works at the server level) and therefore is exclusive to my web development / hosting clients only.

Are you hosting those pages via GitHub? It might the cause of the problem?

Otherwise a bug exists in Instant Click and would likely not be resolved as the original developer seems to have jumped ship a while ago.

**Comment by bobbyshaw** [comment]
I am on github. I had a colleague that removed instant click for the same symptoms but didn't investigate as far as I had into the issue.  It's likely that he hat github pages + cloudflare set up as well. 

Fair enough.  To be honest, I think I've decided to remove it, get the benefits of using HTTPs and HTTP2, and look into progress web app methodology as my strategy for performance rather than this.

Wanted to log it here just in case someone has an idea and/or help other people realise they might not be alone with the issue.

**Comment by dieulot** [comment]
What’s happening is that https://tomrobertshaw.net/projects miss a trailing slash, so the web server makes a redirection to add it (with InstantClick or without). The server redirects to the HTTP version though[1]. So InstantClick preloads an HTTPS page but ends up being redirect to an HTTP page.

If you’re on an HTTPS page, InstantClick (and XMLHttpRequest in general) needs HTTPS all the way in Ajax requests.

That it requires a second click to go to the page is a bug though, it should change the `location.href` when a network error occurs. I forgot to handle network errors on click when the page is already loaded. 31c8bd45ceee15b7672d20d6e0c2f87f81a71f32 should do the trick (though I haven’t formally tested it over HTTPS).

\[1]: Most likely because CloudFlare communicates with it over HTTP and the server isn't aware that it is in fact served as HTTPS.

**Comment by bobbyshaw** [comment]
Thanks for looking into it and the write-up @dieulot.

**Comment by Harmonicorps** [comment]
https://github.com/dieulot/instantclick/issues/151
ElectricDuck and I are both having issues with this. I'm not using cloudflare.
I'm using a fork of this site. https://github.com/TaylanTatli/Moon
